/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Compi;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Point;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Luis Cota
 */
public class frmCompi extends javax.swing.JFrame {

    /**
     * Creates new form frmCompi
     */
    
    Point initialClick;
    int x, y;
    ImageIcon icon;
    StateMachine SM;
    Sytaxis S;
    CreateCode C;
    boolean visible;
    public frmCompi() {
        initComponents();
        this.setLocationRelativeTo(null);
        SM = new StateMachine();
        S = new Sytaxis();
        C = new CreateCode();
        visible = true;
        AWTUtilities.setWindowOpaque(this, false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.black);
        jPanel1.setPreferredSize(new java.awt.Dimension(170, 220));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Checar Tokens");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Comprobar");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jSeparator3.setBackground(java.awt.Color.white);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 10));

        jSeparator5.setBackground(java.awt.Color.white);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 160, 10));

        jSeparator6.setBackground(java.awt.Color.white);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 160, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 0, 0));

        jPanel2.setBackground(java.awt.Color.black);
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CloseWhite.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1520, 10, -1, -1));
        jLabel1.getAccessibleContext().setAccessibleName("Close");
        jLabel1.getAccessibleContext().setAccessibleParent(this);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MinimizeWhite.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/MenuWhite.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UpWhite.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 50));

        jTextPane1.setBackground(new java.awt.Color(51, 51, 51));
        jTextPane1.setBorder(null);
        jTextPane1.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        jTextPane1.setForeground(new java.awt.Color(0, 102, 51));
        jScrollPane2.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 1090, 710));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(51, 51, 51));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        jTextArea1.setForeground(java.awt.Color.white);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 460, 640));

        jComboBox1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Palabras", "Numeros Enteros", "Numeros Decimales", "Puntos", "Puntos y Coma", "Comas", "Parentecis Inicio", "Parentecis Final ", "Llave Inicio ", "Llave Final ", "Corchete Inicio ", "Corchete Final ", "Mas", "Menos ", "Asteriscos", "Slashes", "Porcentajes", "Iguales", "Desigualdades ", "Menor", "Mayor", "Menor Igual", "Mayor Igual", "Asignaciones", "Comillas", "And", "Or", "Not", "If", "Else", "For", "Break", "Continue", "True", "False", "Scan", "Print", "Go ", "Package", "Main", "Func", "Var", "Const", "Type", "Int", "String", "Bool", "Float" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 460, 30));

        jPanel3.setBackground(java.awt.Color.black);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Cantidad: 0");
        jLabel4.setToolTipText("");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 460, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        icon = new ImageIcon("src/img/MinimizeWhite.png");
        jLabel2.setIcon(icon);
        setExtendedState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        icon = new ImageIcon("src/img/CloseRed.png");
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        icon = new ImageIcon("src/img/CloseWhite.png");
        jLabel1.setIcon(icon);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        icon = new ImageIcon("src/img/MinimizeBlue.png");
        jLabel2.setIcon(icon);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        icon = new ImageIcon("src/img/MinimizeWhite.png");
        jLabel2.setIcon(icon);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        jPanel1.setSize(165, 85);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        icon = new ImageIcon("src/img/MenuGrey.png");
        jLabel3.setIcon(icon);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        icon = new ImageIcon("src/img/MenuWhite.png");
        jLabel3.setIcon(icon);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setSize(0, 0);
    }//GEN-LAST:event_jPanel1MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        jPanel1.setSize(165, 85);
        jLabel6.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jPanel1.setSize(165, 85);
        jLabel7.setForeground(Color.GRAY);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        jPanel1.setSize(0, 0);
        String texto = "";
        /*for(Variable item : S.Variables){
                //texto += " "+item.getText()+"  "+item.getRenglon()+"  "+item.getTipo()+"\n\r";
                texto += " "+item.getVariable()+"  "+item.getTipo()+"\n\r";
                jTextArea1.setText(texto);
        }*/
        /*for(Integer i : S.PosFijo){
                texto += " "+i+"\n\r";
                jTextArea1.setText(texto);
        }*/
        for(PolishItem i : S.Polish){
                texto += " "+i.getTexto()+ "\t"+i.getTicket()+ "\t"+i.getTipo() +"\n\r";
                jTextArea1.setText(texto);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        jPanel1.setSize(0, 0);
        jTextPane1.setText("");
        jTextArea1.setText("");
        String path = "C:" + File.separator + "Users" + File.separator + "Luis Cota" + File.separator + "Desktop" + File.separator + "Compi" + File.separator + "Prueba.go";
        File f = new File(path);
        try{
            FileInputStream fi = new FileInputStream(f);
            SM.Items.clear();
            //String mensaje = SM.StateM(fi, jTextPane1);
            SM.StateM(fi, jTextPane1);
            if(!SM.Error.equals("")){
                JOptionPane.showMessageDialog(null, SM.Error);
            }
            else{
                S.SyntaxisGO(SM.Items);
                if(!S.Error.equals("")){
                    if(!SM.Items.isEmpty()){
                        if(S.currentIndex > 0) S.currentIndex--;
                        JOptionPane.showMessageDialog(null, S.Error+"\n\rEn el renglon "+SM.Items.get(S.currentIndex).getRenglon());
                    }
                }
                else{
                    String path1 = "C:" + File.separator + "TASM" + File.separator + "prueba.asm";
                    FileWriter write = new FileWriter(path1);
                    PrintWriter printLine = new PrintWriter(write);
                    String primera_parte = "INCLUDE macros.mac\n" +
                                            "DOSSEG\n" +
                                            ".MODEL SMALL\n" +
                                            "STACK 100h";
                    String variables = "\n.DATA\n" +
                        "			BUFFER		DB 8 DUP('$')  ;23h\n" +
                        "			BUFFERTEMP	DB 8 DUP('$')  ;23h\n" +
                        "			n_line DB 0AH,0DH,\"$\"\n"+
                        "			BLANCO	DB '#'\n" +
                        "			BLANCOS	DB '$'\n" +
                        "			MENOS	DB '-$'\n" +
                        "			COUNT	DW 0\n" +
                        "			NEGATIVO	DB 0\n" +
                        "			ARREGLO	DW 0\n" +
                        "			ARREGLO1	DW 0\n" +
                        "			ARREGLO2	DW 0\n" +
                        "			LISTAPAR	LABEL BYTE\n" +
                        "			LONGMAX	DB 254\n" +
                        "			TOTCAR	DB ?\n" +
                        "			INTRODUCIDOS	DB 254 DUP ('$')\n" +
                        "			MULT10	DW 1\n" +
                        "			t1 dw ?\n" +
                        "			t2 dw ?\n" +
                        "			t3 dw ?\n" +
                        "			temp dw ?\n" +
                        "			num1 dw 0\n" +
                        "			num2 dw 0\n" +
                        "			num3 dw 0\n" +
                        "			num4 dw 0\n" +
                        "			ten dw 10\n"+
                        "			cadena db 'Hola Mundo','$'\n" + 
                        "                       RESULT     DB 6 DUP('$')\n" +
                        "			TMP1       DW ?\n";
                    variables = C.putVariables(S.Variables, variables);
                    String segunda_parte = "\n.CODE\n" +
                                            ".386\n" +
                                            "BEGIN:\n" +
                                            "			MOV     AX, @DATA\n" +
                                            "			MOV     DS, AX\n" +
                                            "CALL  COMPI\n" +
                                            "			MOV AX, 4C00H\n" +
                                            "			INT 21H\n" +
                                            "COMPI  PROC\n\n";
                    String codigo = C.makeCode(S.Polish, "", S.Variables);
                    //String codigo ="";
                    variables += C.masVars;
                    String ultima_parte = "\nret\n" +
                                        "COMPI  ENDP\n" +
                                        "END BEGIN";
                    printLine.printf("%s"+"%n", primera_parte + variables + segunda_parte + codigo + ultima_parte);
                    printLine.close();
                    try {
                        ProcessBuilder pb = new ProcessBuilder("C:\\Program Files (x86)\\DOSBox-0.74-2\\DOSBox.exe", "dosbox", "-c", "mount c c:\\tasm", "dosbox", "-c", "c:", 
                                "dosbox", "-c", "tasm prueba.asm", "dosbox", "-c", "tlink prueba.obj", "dosbox", "-c", "prueba.exe");
                        pb.redirectError();
                        Process p = pb.start();
                        new Thread(new InputStreamConsumer(p.getInputStream())).start();
                        System.out.println("Have exited with " + p.waitFor());
                    } catch (IOException | InterruptedException exp) {
                        exp.printStackTrace();
                    }
                }
            }
            getTokens();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "No se pudo acceder al archivo correctamente");
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        getTokens();
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        if(visible){
            icon = new ImageIcon("src/img/DownGrey.png");
            jLabel5.setIcon(icon);
            visible(false);
            visible = false;
        }
        else{
            icon = new ImageIcon("src/img/UpGrey.png");
            jLabel5.setIcon(icon);
            visible(true);
            visible = true;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        if(visible){
            icon = new ImageIcon("src/img/UpGrey.png");
            jLabel5.setIcon(icon);
        }
        else{
            icon = new ImageIcon("src/img/DownGrey.png");
            jLabel5.setIcon(icon);
        } 
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        if(visible){
            icon = new ImageIcon("src/img/UpWhite.png");
            jLabel5.setIcon(icon);
        }
        else{
            icon = new ImageIcon("src/img/DownWhite.png");
            jLabel5.setIcon(icon);
        }
    }//GEN-LAST:event_jLabel5MouseExited

    void getTokens(){
        jTextArea1.setText("");
        int token = 0, c = 0;
        switch(jComboBox1.getSelectedIndex()){
            case 0:
                token = 100;
                break;
            case 1:
                token = 101;
                break;
            case 2:
                token = 102;
                break;
            case 3:
                token = 103;
                break;
            case 4:
                token = 104;
                break;
            case 5:
                token = 105;
                break;
            case 6:
                token = 107;
                break;
            case 7:
                token = 108;
                break;
            case 8:
                token = 109;
                break;
            case 9:
                token = 110;
                break;
            case 10:
                token = 111;
                break;
            case 11:
                token = 112;
                break;
            case 12:
                token = 113;
                break;
            case 13:
                token = 114;
                break;
            case 14:
                token = 115;
                break;
            case 15:
                token = 116;
                break;
            case 16:
                token = 117;
                break;
            case 17:
                token = 118;
                break;
            case 18:
                token = 119;
                break;
            case 19:
                token = 120;
                break;
            case 20:
                token = 121;
                break;
            case 21:
                token = 122;
                break;
            case 22:
                token = 123;
                break;
            case 23:
                token = 124;
                break;
            case 24:
                token = 125;
                break;
            case 25:
                token = 126;
                break;
            case 26:
                token = 127;
                break;
            case 27:
                token = 128;
                break;
            case 28:
                token = 200;
                break;
            case 29:
                token = 201;
                break;
            case 30:
                token = 202;
                break;
            case 31:
                token = 203;
                break;
            case 32:
                token = 204;
                break;
            case 33:
                token = 205;
                break;
            case 34:
                token = 206;
                break;
            case 35:
                token = 207;
                break;
            case 36:
                token = 208;
                break;
            case 37:
                token = 209;
                break;
            case 38:
                token = 210;
                break;
            case 39:
                token = 211;
                break;
            case 40:
                token = 212;
                break;
            case 41:
                token = 213;
                break;
            case 42:
                token = 214;
                break;
            case 43:
                token = 215;
                break;
            case 44:
                token = 216;
                break;
            case 45:
                token = 217;
                break;
            case 46:
                token = 218;
                break;
            case 47:
                token = 219;
                break;
        }
        String texto = "";
        for(Item item : SM.Items){
            //if(item.getTipo() == token){
                texto += " "+item.getText()+"  "+item.getRenglon()+"  "+item.getTipo()+"\n\r";
                c++;
                jTextArea1.setText(texto);
            //}
        }
        jLabel4.setText("Cantidad: "+c);
    }
    
    void visible(boolean visible){
        jComboBox1.setVisible(visible);
        jScrollPane1.setVisible(visible);
        jScrollPane2.setVisible(visible);
        jPanel3.setVisible(visible);
    }
    
    public static class InputStreamConsumer implements Runnable {

        private InputStream is;

        public InputStreamConsumer(InputStream inputStream) {
            is = inputStream;
        }

        @Override
        public void run() {
            int in = -1;
            try {
                while ((in = is.read()) != -1) {
                    System.out.print((char) in);
                }
            } catch (IOException exp) {
                exp.printStackTrace();
            }
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCompi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCompi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCompi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCompi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCompi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
